Repository atharva-narkhede/Cpp-Codes, pull requests merged in 2022-10, with the labels that each got.

#2 Update fibonacci_series_iterative.cpp
  Fibonacci Codes/fibonacci_series_iterative.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#3 Create QuickSort.cpp
  QuickSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#4 Create Mergesort.cpp
  Mergesort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#5 Update bubble_sort.cpp
  DAA/bubble_sort.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#6 Update insertion.cpp
  DAA/insertion.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#7 Update Knapsack.cpp
  DAA/Knapsack.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#8 Create kruskal.cpp
  DAA/kruskal.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#11 Added Dijkstra's Algorithm
  DAA/Dijkstra'sAlgorithm.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#10 Create linear_search.cpp
  DAA/linear_search.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#12 Selection_Sort.cpp
  DAA/selection_sort.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#13 Create Atm.cpp
  OOPs/Atm.cpp
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#14 Create Exchange_number.cpp
  OOPs/Exchange_number.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#15 Create complexmethod.cpp
  OOPs/complexmethod.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#17 Create prims.cpp
  DAA/prims.cpp
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#18 Defined UserInput
  Fibonacci Codes/Fibonacci_using_recursion.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#19 MergeSort
  DAA/merge_sort.cpp
  Fibonacci Codes/Fibonacci_using_recursion.exe
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#20 Reorder Linked List
  .vscode/settings.json
  DAA/ReorderLinkedList.cpp
  DAA/SelectionSort.cpp
Labels: documentation, good first issue, hacktoberfest-accepted, hacktoberfest

#21 Substraction In Linked List
  DAA/SubstractionLinkedList.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#22 Create BST.cpp
  DSA/BST.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest

#23 Create star_pattern.cpp
  C++/star_pattern.cpp
Labels: documentation, hacktoberfest-accepted, hacktoberfest
